// Copyright 2023 Raven Industries inc.

// todo!("Implement all IndustryGroup specific FunctionCode's");

/// Enum containing all Function Code's.
///
/// # Examples
///
/// ```rust
/// # use ag_iso_stack::network_management::name::{IndustryGroup, FunctionCode};
/// let function_code: FunctionCode = FunctionCode::VirtualTerminal;
///
/// assert_eq!(function_code, FunctionCode::from(29));
/// assert_eq!(function_code, 29.into());
/// assert_eq!(29, u8::from(function_code));
/// assert_eq!(29_u8, function_code.into());
/// ```
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default)]
pub enum FunctionCode {
    // Shared
    #[default]
    NotAvailable,

    // Global
    Engine,
    AuxiliaryPowerUnit,
    ElectricPropulsionControl,
    Transmission,
    BatteryPackMonitor,
    ShiftControlConsole,
    PowerTakeOffMain,
    AxleSteering,
    AxleDrive,
    BrakesSystemController,
    BrakesSteerAxle,
    BrakesDriveAxle,
    RetarderEngine,
    RetarderDriveline,
    CruiseControl,
    FuelSystem,
    SteeringController,
    SuspensionSteerAxle,
    SuspensionDriveAxle,
    InstrumentCluster,
    TripRecorder,
    CabClimateControl,
    AerodynamicControl,
    VehicleNavigation,
    VehicleSecurity,
    NetworkInterconnectECU,
    BodyController,
    PowerTakeOffSecondary,
    OffVehicleGateway,
    VirtualTerminal,
    ManagementComputer,
    PropulsionBatteryCharger,
    HeadwayController,
    SystemMonitor,
    HydraulicPumpController,
    SuspensionSystemController,
    PneumaticSystemController,
    CabController,
    TirePressureControl,
    IgnitionControlModule,
    SeatControl,
    LightingOperatorControls,
    WaterPumpControl,
    TransmissionDisplay,
    ExhaustEmissionControl,
    VehicleDynamicStabilityControl,
    OilSensorUnit,
    InformationSystemController,
    RampControl,
    ClutchConverterControl,
    AuxiliaryHeater,
    ForwardLookingCollisionWarningSystem,
    ChassisController,
    AlternatorChargingSystem,
    CommunicationsUnitCellular,
    CommunicationsUnitSatellite,
    CommunicationsUnitRadio,
    SteeringColumnUnit,
    FanDriveControl,
    Starter,
    CabDisplay,
    FileServerPrinter,
    OnBoardDiagnosticUnit,
    EngineValveController,
    EnduranceBraking,
    GasFlowMeasurement,
    IOController,
    ElectricalSystemController,
    AfterTreatmentSystemGasMeasurement,
    EngineEmissionAfterTreatmentSystem,
    AuxiliaryRegenerationDevice,
    TransferCaseControl,
    CoolantValveController,
    RolloverDetectionControl,
    LubricationSystem,
    SupplementalFan,
    TemperatureSensor,
    FuelPropertiesSensor,
    FireSuppressionSystem,
    PowerSystemsManager,
    ElectricPowertrain,
    HydraulicPowertrain,
    FileServer,
    Printer,
    StartAidDevice,
    EngineInjectionControlModule,
    EVCommunicationController,
    DriverImpairmentDevice,
    ElectricPowerConverter,
    SupplyEquipmentCommunicationController,
    VehicleAdapterCommunicationController,
    Reserved,
    OffBoardDiagnosticServiceTool,
    OnBoardDataLogger,
    PCKeyboard,
    SafetyRestraintSystem,
    Turbocharger,
    GroundBasedSpeedSensor,
    Keypad,
    HumiditySensor,
    ThermalManagementSystemController,
    BrakeStrokeAlert,
    OnBoardAxleGroupScale,
    OnBoardAxleGroupDisplay,
    BatteryCharger,
    TurbochargerCompressorBypass,
    TurbochargerWastegate,
    Throttle,
    InertialSensor,
    FuelActuator,
    EngineExhaustGasRecirculation,
    EngineExhaustBackpressure,
    OnBoardBinWeighingScale,
    OnBoardBinWeighingScaleDisplay,
    EngineCylinderPressureMonitoringSystem,
    ObjectDetection,
    ObjectDetectionDisplay,
    ObjectDetectionSensor,
    PersonnelDetectionDevice,
}

/// Display the Function Code name.
///
/// # Examples
///
/// ```rust
/// # use ag_iso_stack::network_management::name::FunctionCode;
///
/// assert_eq!("VirtualTerminal", format!("{}", FunctionCode::VirtualTerminal));
/// ```
impl core::fmt::Display for FunctionCode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}", self)
    }
}

/// Convert a `FunctionCode` into a u8.
///
/// # Examples
///
/// ```rust
/// # use ag_iso_stack::network_management::name::FunctionCode;
///
/// assert_eq!(29, u8::from(FunctionCode::VirtualTerminal));
/// assert_eq!(29_u8, FunctionCode::VirtualTerminal.into());
/// ```
impl From<FunctionCode> for u8 {
    fn from(value: FunctionCode) -> Self {
        match value {
            // Shared
            FunctionCode::NotAvailable => 127,

            // Global
            FunctionCode::Engine => 0,
            FunctionCode::AuxiliaryPowerUnit => 1,
            FunctionCode::ElectricPropulsionControl => 2,
            FunctionCode::Transmission => 3,
            FunctionCode::BatteryPackMonitor => 4,
            FunctionCode::ShiftControlConsole => 5,
            FunctionCode::PowerTakeOffMain => 6,
            FunctionCode::AxleSteering => 7,
            FunctionCode::AxleDrive => 8,
            FunctionCode::BrakesSystemController => 9,
            FunctionCode::BrakesSteerAxle => 10,
            FunctionCode::BrakesDriveAxle => 11,
            FunctionCode::RetarderEngine => 12,
            FunctionCode::RetarderDriveline => 13,
            FunctionCode::CruiseControl => 14,
            FunctionCode::FuelSystem => 15,
            FunctionCode::SteeringController => 16,
            FunctionCode::SuspensionSteerAxle => 17,
            FunctionCode::SuspensionDriveAxle => 18,
            FunctionCode::InstrumentCluster => 19,
            FunctionCode::TripRecorder => 20,
            FunctionCode::CabClimateControl => 21,
            FunctionCode::AerodynamicControl => 22,
            FunctionCode::VehicleNavigation => 23,
            FunctionCode::VehicleSecurity => 24,
            FunctionCode::NetworkInterconnectECU => 25,
            FunctionCode::BodyController => 26,
            FunctionCode::PowerTakeOffSecondary => 27,
            FunctionCode::OffVehicleGateway => 28,
            FunctionCode::VirtualTerminal => 29,
            FunctionCode::ManagementComputer => 30,
            FunctionCode::PropulsionBatteryCharger => 31,
            FunctionCode::HeadwayController => 32,
            FunctionCode::SystemMonitor => 33,
            FunctionCode::HydraulicPumpController => 34,
            FunctionCode::SuspensionSystemController => 35,
            FunctionCode::PneumaticSystemController => 36,
            FunctionCode::CabController => 37,
            FunctionCode::TirePressureControl => 38,
            FunctionCode::IgnitionControlModule => 39,
            FunctionCode::SeatControl => 40,
            FunctionCode::LightingOperatorControls => 41,
            FunctionCode::WaterPumpControl => 42,
            FunctionCode::TransmissionDisplay => 43,
            FunctionCode::ExhaustEmissionControl => 44,
            FunctionCode::VehicleDynamicStabilityControl => 45,
            FunctionCode::OilSensorUnit => 46,
            FunctionCode::InformationSystemController => 47,
            FunctionCode::RampControl => 48,
            FunctionCode::ClutchConverterControl => 49,
            FunctionCode::AuxiliaryHeater => 50,
            FunctionCode::ForwardLookingCollisionWarningSystem => 51,
            FunctionCode::ChassisController => 52,
            FunctionCode::AlternatorChargingSystem => 53,
            FunctionCode::CommunicationsUnitCellular => 54,
            FunctionCode::CommunicationsUnitSatellite => 55,
            FunctionCode::CommunicationsUnitRadio => 56,
            FunctionCode::SteeringColumnUnit => 57,
            FunctionCode::FanDriveControl => 58,
            FunctionCode::Starter => 59,
            FunctionCode::CabDisplay => 60,
            FunctionCode::FileServerPrinter => 61,
            FunctionCode::OnBoardDiagnosticUnit => 62,
            FunctionCode::EngineValveController => 63,
            FunctionCode::EnduranceBraking => 64,
            FunctionCode::GasFlowMeasurement => 65,
            FunctionCode::IOController => 66,
            FunctionCode::ElectricalSystemController => 67,
            FunctionCode::AfterTreatmentSystemGasMeasurement => 68,
            FunctionCode::EngineEmissionAfterTreatmentSystem => 69,
            FunctionCode::AuxiliaryRegenerationDevice => 70,
            FunctionCode::TransferCaseControl => 71,
            FunctionCode::CoolantValveController => 72,
            FunctionCode::RolloverDetectionControl => 73,
            FunctionCode::LubricationSystem => 74,
            FunctionCode::SupplementalFan => 75,
            FunctionCode::TemperatureSensor => 76,
            FunctionCode::FuelPropertiesSensor => 77,
            FunctionCode::FireSuppressionSystem => 78,
            FunctionCode::PowerSystemsManager => 79,
            FunctionCode::ElectricPowertrain => 80,
            FunctionCode::HydraulicPowertrain => 81,
            FunctionCode::FileServer => 82,
            FunctionCode::Printer => 83,
            FunctionCode::StartAidDevice => 84,
            FunctionCode::EngineInjectionControlModule => 85,
            FunctionCode::EVCommunicationController => 86,
            FunctionCode::DriverImpairmentDevice => 87,
            FunctionCode::ElectricPowerConverter => 88,
            FunctionCode::SupplyEquipmentCommunicationController => 89,
            FunctionCode::VehicleAdapterCommunicationController => 90,
            FunctionCode::Reserved => 128,
            FunctionCode::OffBoardDiagnosticServiceTool => 129,
            FunctionCode::OnBoardDataLogger => 130,
            FunctionCode::PCKeyboard => 131,
            FunctionCode::SafetyRestraintSystem => 132,
            FunctionCode::Turbocharger => 133,
            FunctionCode::GroundBasedSpeedSensor => 134,
            FunctionCode::Keypad => 135,
            FunctionCode::HumiditySensor => 136,
            FunctionCode::ThermalManagementSystemController => 137,
            FunctionCode::BrakeStrokeAlert => 138,
            FunctionCode::OnBoardAxleGroupScale => 139,
            FunctionCode::OnBoardAxleGroupDisplay => 140,
            FunctionCode::BatteryCharger => 141,
            FunctionCode::TurbochargerCompressorBypass => 142,
            FunctionCode::TurbochargerWastegate => 143,
            FunctionCode::Throttle => 144,
            FunctionCode::InertialSensor => 145,
            FunctionCode::FuelActuator => 146,
            FunctionCode::EngineExhaustGasRecirculation => 147,
            FunctionCode::EngineExhaustBackpressure => 148,
            FunctionCode::OnBoardBinWeighingScale => 149,
            FunctionCode::OnBoardBinWeighingScaleDisplay => 150,
            FunctionCode::EngineCylinderPressureMonitoringSystem => 151,
            FunctionCode::ObjectDetection => 152,
            FunctionCode::ObjectDetectionDisplay => 153,
            FunctionCode::ObjectDetectionSensor => 154,
            FunctionCode::PersonnelDetectionDevice => 155,
        }
    }
}

/// Convert a u8 into a `FunctionCode`.
///
/// # Examples
///
/// ```rust
/// # use ag_iso_stack::network_management::name::FunctionCode;
///
/// assert_eq!(FunctionCode::VirtualTerminal, FunctionCode::from(29));
/// assert_eq!(FunctionCode::VirtualTerminal, 29.into());
/// ```
impl From<u8> for FunctionCode {
    fn from(value: u8) -> Self {
        match value {
            0 => FunctionCode::Engine,
            1 => FunctionCode::AuxiliaryPowerUnit,
            2 => FunctionCode::ElectricPropulsionControl,
            3 => FunctionCode::Transmission,
            4 => FunctionCode::BatteryPackMonitor,
            5 => FunctionCode::ShiftControlConsole,
            6 => FunctionCode::PowerTakeOffMain,
            7 => FunctionCode::AxleSteering,
            8 => FunctionCode::AxleDrive,
            9 => FunctionCode::BrakesSystemController,
            10 => FunctionCode::BrakesSteerAxle,
            11 => FunctionCode::BrakesDriveAxle,
            12 => FunctionCode::RetarderEngine,
            13 => FunctionCode::RetarderDriveline,
            14 => FunctionCode::CruiseControl,
            15 => FunctionCode::FuelSystem,
            16 => FunctionCode::SteeringController,
            17 => FunctionCode::SuspensionSteerAxle,
            18 => FunctionCode::SuspensionDriveAxle,
            19 => FunctionCode::InstrumentCluster,
            20 => FunctionCode::TripRecorder,
            21 => FunctionCode::CabClimateControl,
            22 => FunctionCode::AerodynamicControl,
            23 => FunctionCode::VehicleNavigation,
            24 => FunctionCode::VehicleSecurity,
            25 => FunctionCode::NetworkInterconnectECU,
            26 => FunctionCode::BodyController,
            27 => FunctionCode::PowerTakeOffSecondary,
            28 => FunctionCode::OffVehicleGateway,
            29 => FunctionCode::VirtualTerminal,
            30 => FunctionCode::ManagementComputer,
            31 => FunctionCode::PropulsionBatteryCharger,
            32 => FunctionCode::HeadwayController,
            33 => FunctionCode::SystemMonitor,
            34 => FunctionCode::HydraulicPumpController,
            35 => FunctionCode::SuspensionSystemController,
            36 => FunctionCode::PneumaticSystemController,
            37 => FunctionCode::CabController,
            38 => FunctionCode::TirePressureControl,
            39 => FunctionCode::IgnitionControlModule,
            40 => FunctionCode::SeatControl,
            41 => FunctionCode::LightingOperatorControls,
            42 => FunctionCode::WaterPumpControl,
            43 => FunctionCode::TransmissionDisplay,
            44 => FunctionCode::ExhaustEmissionControl,
            45 => FunctionCode::VehicleDynamicStabilityControl,
            46 => FunctionCode::OilSensorUnit,
            47 => FunctionCode::InformationSystemController,
            48 => FunctionCode::RampControl,
            49 => FunctionCode::ClutchConverterControl,
            50 => FunctionCode::AuxiliaryHeater,
            51 => FunctionCode::ForwardLookingCollisionWarningSystem,
            52 => FunctionCode::ChassisController,
            53 => FunctionCode::AlternatorChargingSystem,
            54 => FunctionCode::CommunicationsUnitCellular,
            55 => FunctionCode::CommunicationsUnitSatellite,
            56 => FunctionCode::CommunicationsUnitRadio,
            57 => FunctionCode::SteeringColumnUnit,
            58 => FunctionCode::FanDriveControl,
            59 => FunctionCode::Starter,
            60 => FunctionCode::CabDisplay,
            61 => FunctionCode::FileServerPrinter,
            62 => FunctionCode::OnBoardDiagnosticUnit,
            63 => FunctionCode::EngineValveController,
            64 => FunctionCode::EnduranceBraking,
            65 => FunctionCode::GasFlowMeasurement,
            66 => FunctionCode::IOController,
            67 => FunctionCode::ElectricalSystemController,
            68 => FunctionCode::AfterTreatmentSystemGasMeasurement,
            69 => FunctionCode::EngineEmissionAfterTreatmentSystem,
            70 => FunctionCode::AuxiliaryRegenerationDevice,
            71 => FunctionCode::TransferCaseControl,
            72 => FunctionCode::CoolantValveController,
            73 => FunctionCode::RolloverDetectionControl,
            74 => FunctionCode::LubricationSystem,
            75 => FunctionCode::SupplementalFan,
            76 => FunctionCode::TemperatureSensor,
            77 => FunctionCode::FuelPropertiesSensor,
            78 => FunctionCode::FireSuppressionSystem,
            79 => FunctionCode::PowerSystemsManager,
            80 => FunctionCode::ElectricPowertrain,
            81 => FunctionCode::HydraulicPowertrain,
            82 => FunctionCode::FileServer,
            83 => FunctionCode::Printer,
            84 => FunctionCode::StartAidDevice,
            85 => FunctionCode::EngineInjectionControlModule,
            86 => FunctionCode::EVCommunicationController,
            87 => FunctionCode::DriverImpairmentDevice,
            88 => FunctionCode::ElectricPowerConverter,
            89 => FunctionCode::SupplyEquipmentCommunicationController,
            90 => FunctionCode::VehicleAdapterCommunicationController,
            128 => FunctionCode::Reserved,
            129 => FunctionCode::OffBoardDiagnosticServiceTool,
            130 => FunctionCode::OnBoardDataLogger,
            131 => FunctionCode::PCKeyboard,
            132 => FunctionCode::SafetyRestraintSystem,
            133 => FunctionCode::Turbocharger,
            134 => FunctionCode::GroundBasedSpeedSensor,
            135 => FunctionCode::Keypad,
            136 => FunctionCode::HumiditySensor,
            137 => FunctionCode::ThermalManagementSystemController,
            138 => FunctionCode::BrakeStrokeAlert,
            139 => FunctionCode::OnBoardAxleGroupScale,
            140 => FunctionCode::OnBoardAxleGroupDisplay,
            141 => FunctionCode::BatteryCharger,
            142 => FunctionCode::TurbochargerCompressorBypass,
            143 => FunctionCode::TurbochargerWastegate,
            144 => FunctionCode::Throttle,
            145 => FunctionCode::InertialSensor,
            146 => FunctionCode::FuelActuator,
            147 => FunctionCode::EngineExhaustGasRecirculation,
            148 => FunctionCode::EngineExhaustBackpressure,
            149 => FunctionCode::OnBoardBinWeighingScale,
            150 => FunctionCode::OnBoardBinWeighingScaleDisplay,
            151 => FunctionCode::EngineCylinderPressureMonitoringSystem,
            152 => FunctionCode::ObjectDetection,
            153 => FunctionCode::ObjectDetectionDisplay,
            154 => FunctionCode::ObjectDetectionSensor,
            155 => FunctionCode::PersonnelDetectionDevice,
            _ => FunctionCode::NotAvailable,
        }
    }
}
